kafka.bootstrap-servers=localhost:9093
kafka.topic=synthetic-events
kafka.group-id=synthetic-consumer-group

# mTLS
kafka.ssl.keystore-location=/etc/kafka/ssl/client.keystore.jks
kafka.ssl.keystore-password=changeit
kafka.ssl.truststore-location=/etc/kafka/ssl/client.truststore.jks
kafka.ssl.truststore-password=changeit

# Schema Registry
kafka.schema-registry.url=http://localhost:8081

# Producer
kafka.producer.rate-per-second=1

# Consumer
kafka.consumer.auto-offset-reset=earliest
