kafka.bootstrap-servers=localhost:9093
kafka.ssl.enabled=true
kafka.ssl.keystore-location=/etc/kafka/ssl/client.keystore.jks
kafka.ssl.keystore-password=changeit
kafka.ssl.truststore-location=/etc/kafka/ssl/client.truststore.jks
kafka.ssl.truststore-password=changeit
server.port=8080
