apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configOverrides }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
